before_install:
  - ./scripts/install_dependencies.sh
  - ./quantasma-app/src/main/resources/scripts/install_services.sh
language: java
jdk:
  - oraclejdk9
  - openjdk9
  - openjdk10
  - openjdk11
  - oraclejdk11
script: mvn test -B
