server:
  port: 8080

service:
  historical-data:
    enabled: false
    prefix: dukascopy
  live-data:
    enabled: false
  backtest:
    enabled: false

spring:
  data:
    mongodb:
      host: 172.17.0.2
      port: 27017
      database: historical
  profiles:
    active: dukascopy

---

spring:
  profiles: mock
service:
  historical-data:
    prefix: mock
